version: "2"
volumes:
    postgres11-postgis2.5:
services:
    postgres:
        build:
            context: .
            dockerfile: Dockerfile
        image: postgres11-postgis2.5
        container_name: postgres11-postgis2.5
        volumes:
            - postgres11-postgis2.5:/var/lib/postgresql/data
            - ./backups:/opt/backups
        networks:
            - postgres_conn
        ports:
            - "5432:5432"
        env_file: .env

networks:
    postgres_conn:
        driver: bridge
