version: "3"

volumes:
  data-mysql:
services:
  db:
    container_name: mysql-dev
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db
