version: "3"

volumes:
  data-sqlserver:
services:
  db:
    container_name: sqlserver-dev
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    ports:
      - "1433:1433"
    volumes:
      - data-sqlserver:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=!sqlServerDev##
