version: "3"

volumes:
  data-postgres-2:
services:
  db:
    container_name: postgres-dev-2
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data-postgres-2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
